=head1 NAME

downloads last.fm profiles and helps scrobbling from files or radio stations

=head1 DESCRIPTION

dl_lfm has several functions, it

* downloads a last.fm profile

* helps scrobbling from json files, radio streaming stations (using vlc) or some 
webpages (supported: bandcamp.com and experimentally youtube.com)

* plays and scrobbles randomly picked tracks from bandcamp.com like a radio 
(needs mplayer installed)

=head1 MOVED

moved to gitlab: https://gitlab.com/wp-seth/dl_lfm
